## About...

This project is an interactive machine learning simulator that helps students and educators understand how factors like study time, attendance, and learning environment affect academic performance. Users can adjust inputs and instantly see how predicted scores change.

#### Target
final score

#### Features
study_hours,
attendance_rate,
past_exam_scores,
parental_education,
internet_access,
extracurricular_activities

In [1]:
import pandas as pd
import numpy as np 

# Load dataset
df = pd.read_csv("../data/raw/student_performance_dataset.csv")

# Preview
df.head()

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

,Student_ID,Gender,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score,Pass_Fail
0,S147,Male,31,68.267841,86,High School,Yes,Yes,63,Pass
1,S136,Male,16,78.222927,73,PhD,No,No,50,Fail
2,S209,Female,21,87.525096,74,PhD,Yes,No,55,Fail
3,S458,Female,27,92.076483,99,Bachelors,No,No,65,Pass
4,S078,Female,37,98.655517,63,Masters,No,Yes,70,Pass

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  708 non-null    object
 1   Gender                      708 non-null    object
 2   Study_Hours_per_Week        708 non-null    int64
 3   Attendance_Rate             708 non-null    float64
 4   Past_Exam_Scores            708 non-null    int64
 5   Parental_Education_Level    708 non-null    object
 6   Internet_Access_at_Home     708 non-null    object
 7   Extracurricular_Activities  708 non-null    object
 8   Final_Exam_Score            708 non-null    int64
 9   Pass_Fail                   708 non-null    object
dtypes: float64(1), int64(3), object(6)
memory usage: 55.4+ KB

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Final_Exam_Score
count,708.000000,708.000000,708.000000,708.000000
mean,26.132768,78.107722,77.871469,58.771186
std,8.877727,13.802802,14.402739,6.705877
min,10.000000,50.116970,50.000000,50.000000
25%,19.000000,67.550094,65.000000,52.000000
50%,27.000000,79.363046,79.000000,59.500000
75%,34.000000,89.504232,91.000000,64.000000
max,39.000000,99.967675,100.000000,77.000000

In [3]:
columns_needed = [
    "Study_Hours_per_Week",
    "Attendance_Rate",
    "Past_Exam_Scores",
    "Parental_Education_Level",
    "Internet_Access_at_Home",
    "Extracurricular_Activities",
    "Final_Exam_Score"
]

df = df[columns_needed]

In [4]:
df.columns

Index(['Study_Hours_per_Week', 'Attendance_Rate', 'Past_Exam_Scores',
       'Parental_Education_Level', 'Internet_Access_at_Home',
       'Extracurricular_Activities', 'Final_Exam_Score'],
      dtype='object')

In [5]:
df.isnull().sum()

Study_Hours_per_Week          0
Attendance_Rate               0
Past_Exam_Scores              0
Parental_Education_Level      0
Internet_Access_at_Home       0
Extracurricular_Activities    0
Final_Exam_Score              0
dtype: int64

In [6]:
df.head()

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score
0,31,68.267841,86,High School,Yes,Yes,63
1,16,78.222927,73,PhD,No,No,50
2,21,87.525096,74,PhD,Yes,No,55
3,27,92.076483,99,Bachelors,No,No,65
4,37,98.655517,63,Masters,No,Yes,70

In [7]:
df["Internet_Access_at_Home"] = df["Internet_Access_at_Home"].map({"Yes": 1, "No": 0})

df["Extracurricular_Activities"] = df["Extracurricular_Activities"].map({"Yes": 1, "No": 0})

In [8]:
df["Parental_Education_Level"].unique()

array(['High School', 'PhD', 'Bachelors', 'Masters'], dtype=object)

In [9]:
df["Parental_Education_Level"] = df["Parental_Education_Level"].map({
    "High School": 0,
    "Bachelors": 1,
    "Masters": 2,
    "PhD":3
})

In [10]:
df.head()

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score
0,31,68.267841,86,0,1,1,63
1,16,78.222927,73,3,0,0,50
2,21,87.525096,74,3,1,0,55
3,27,92.076483,99,1,0,0,65
4,37,98.655517,63,2,0,1,70

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Study_Hours_per_Week        708 non-null    int64
 1   Attendance_Rate             708 non-null    float64
 2   Past_Exam_Scores            708 non-null    int64
 3   Parental_Education_Level    708 non-null    int64
 4   Internet_Access_at_Home     708 non-null    int64
 5   Extracurricular_Activities  708 non-null    int64
 6   Final_Exam_Score            708 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 38.8 KB

In [12]:
df.describe()

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score
count,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000
mean,26.132768,78.107722,77.871469,1.449153,0.461864,0.490113,58.771186
std,8.877727,13.802802,14.402739,1.110048,0.498896,0.500256,6.705877
min,10.000000,50.116970,50.000000,0.000000,0.000000,0.000000,50.000000
25%,19.000000,67.550094,65.000000,0.000000,0.000000,0.000000,52.000000
50%,27.000000,79.363046,79.000000,1.000000,0.000000,0.000000,59.500000
75%,34.000000,89.504232,91.000000,2.000000,1.000000,1.000000,64.000000
max,39.000000,99.967675,100.000000,3.000000,1.000000,1.000000,77.000000

In [13]:
df = df[df["Attendance_Rate"] <= 100]

In [14]:
df.to_csv("../data/processed/cleaned_student_data.csv", index=False)